todo:
  path: /
  controller: App\Controller\TasksController::todo

todo_complete:
  path: /tasks/{id}/complete
  controller: App\Controller\TasksController::complete

tasks_index:
  path: /tasks
  controller: App\Controller\TasksController::index
  methods: [GET]

tasks_create:
  path: /tasks/create
  controller: App\Controller\TasksController::create
  methods: [POST, GET]

tasks_update:
  path: /tasks/{id}/edit
  controller: App\Controller\TasksController::edit
  methods: [POST, GET]

tasks_delete:
  path: /tasks/{id}/delete
  controller: App\Controller\TasksController::delete
  methods: [GET]

tasks_logs:
  path: /tasks/{id}/logs
  controller: App\Controller\TasksController::logs
  methods: [GET]

tasks_history:
  path: /tasks/history
  controller: App\Controller\TasksController:history
  methods: [GET]

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"